/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Democracy__factory } from "./Democracy__factory";
export { Destructable__factory } from "./Destructable__factory";
