/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Faucet__factory } from "./Faucet__factory";
export { SimpleStorage__factory } from "./SimpleStorage__factory";
