/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Democracy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Democracy__factory>;
    getContractFactory(
      name: "Destructable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Destructable__factory>;
    getContractFactory(
      name: "Faucet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Faucet__factory>;
    getContractFactory(
      name: "SimpleStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SimpleStorage__factory>;

    getContractAt(
      name: "Democracy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Democracy>;
    getContractAt(
      name: "Destructable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Destructable>;
    getContractAt(
      name: "Faucet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Faucet>;
    getContractAt(
      name: "SimpleStorage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SimpleStorage>;

    deployContract(
      name: "Democracy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Democracy>;
    deployContract(
      name: "Destructable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Destructable>;
    deployContract(
      name: "Faucet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Faucet>;
    deployContract(
      name: "SimpleStorage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SimpleStorage>;

    deployContract(
      name: "Democracy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Democracy>;
    deployContract(
      name: "Destructable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Destructable>;
    deployContract(
      name: "Faucet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Faucet>;
    deployContract(
      name: "SimpleStorage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SimpleStorage>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
