/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Faucet } from "./Faucet";
export type { SimpleStorage } from "./SimpleStorage";
export * as factories from "./factories";
export { Faucet__factory } from "./factories/Faucet__factory";
export { SimpleStorage__factory } from "./factories/SimpleStorage__factory";
