/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as democracySol from "./Democracy.sol";
export type { democracySol };
export type { Faucet } from "./Faucet";
export type { SimpleStorage } from "./SimpleStorage";
export * as factories from "./factories";
export type { Democracy } from "./Democracy.sol/Democracy";
export { Democracy__factory } from "./factories/Democracy.sol/Democracy__factory";
export type { Destructable } from "./Democracy.sol/Destructable";
export { Destructable__factory } from "./factories/Democracy.sol/Destructable__factory";
export { Faucet__factory } from "./factories/Faucet__factory";
export { SimpleStorage__factory } from "./factories/SimpleStorage__factory";
